apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"fraud-frontend"},"name":"fraud-frontend","namespace":"application"},"spec":{"ports":[{"name":"http","port":80,"targetPort":80}],"selector":{"app":"fraud-frontend"},"type":"ClusterIP"}}
  creationTimestamp: "2026-05-05T23:31:48Z"
  labels:
    app: fraud-frontend
  name: fraud-frontend
  namespace: application
  resourceVersion: "614796"
  uid: 8e66a885-7bb1-476f-8ef3-8721f5386a67
spec:
  clusterIP: 172.20.185.113
  clusterIPs:
  - 172.20.185.113
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fraud-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
